name: hg-beta.test
type: php
docroot: dist
php_version: "8.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.5"
hooks:
    post-start:
        - exec-host: ddev snapshot
project_tld: test
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "16"
bind_all_interfaces: true